#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <vault_path> <thinking|work>"
  exit 1
fi

VAULT_PATH="$1"
VAULT_TYPE="$2"

if [[ "$VAULT_TYPE" != "thinking" && "$VAULT_TYPE" != "work" ]]; then
  echo "Error: vault type must be 'thinking' or 'work'"
  exit 1
fi

mkdir -p "$VAULT_PATH"/{00_inbox,02_reference,03_creating,04_published,05_archive,06_system/MOCs,06_system/templates}

if [[ "$VAULT_TYPE" == "thinking" ]]; then
  mkdir -p "$VAULT_PATH/01_thinking" "$VAULT_PATH/01_thinking/notes" "$VAULT_PATH/01_thinking/synthesis"
  PRIMARY_FOLDER="01_thinking"
else
  mkdir -p "$VAULT_PATH/01_work" "$VAULT_PATH/01_work/projects" "$VAULT_PATH/01_work/clients" "$VAULT_PATH/01_work/synthesis"
  PRIMARY_FOLDER="01_work"
fi

cat > "$VAULT_PATH/06_system/AGENT.md" <<'MD'
# AGENT.md (Codex/OpenClaw)

## Execution Order (mandatory)
1. Read `06_system/INDEX.md`
2. Read relevant files in `06_system/MOCs/`
3. Select top candidate notes (max 8) via precision search
4. If confidence is low, ask before major edits
5. Apply conservative links only when sentence meaning improves
6. If cross-note insight is strong, create synthesis note
7. Update `INDEX.md` + relevant MOC breadcrumbs
8. Commit with structured message

## Linking Policy (precision-first)
- Add links conservatively (high precision)
- Prefer existing canonical notes
- Avoid speculative links
- Typically add no more than 2-4 links per edited note

## Write Policy
- Auto-write is allowed
- Do not destructively rewrite canonical notes without clear rationale
- Keep edits incremental and reviewable

## Output Contract
When finishing a task, report:
- Summary
- Files touched
- Links added
- Synthesis notes created
- Risks/open questions
MD

cat > "$VAULT_PATH/06_system/INDEX.md" <<'MD'
# INDEX

## Canonical Notes (manual override)

- (add high-value canonical notes here)

## Auto Index (generated)

> Generated by `06_system/rebuild_index.sh`
MD

cat > "$VAULT_PATH/06_system/MOCs/README.md" <<'MD'
# MOCs (Maps of Content)

Use MOCs as topic hubs.
Each MOC should include:
- What this topic covers
- Canonical links
- Navigation breadcrumbs for future sessions
- Open questions
MD

cat > "$VAULT_PATH/06_system/templates/claim-note.md" <<'MD'
# {{title}}

## Claim

## Why it matters

## Contextual links

## Evidence / examples

## Reuse
- Use when:
- Avoid when:
MD

cat > "$VAULT_PATH/06_system/templates/synthesis-note.md" <<'MD'
# {{title}}

## Emergent insight
(What appears when combining source notes)

## Source notes
- [[source-note-1]]
- [[source-note-2]]

## Implications

## Follow-up links
MD

cat > "$VAULT_PATH/06_system/rebuild_index.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INDEX="$ROOT/06_system/INDEX.md"
TMP="$(mktemp)"

# Preserve manual section if present
MANUAL_SECTION=""
if [[ -f "$INDEX" ]]; then
  MANUAL_SECTION="$(awk '/^## Canonical Notes \(manual override\)/{flag=1} /^## Auto Index \(generated\)/{flag=0} flag{print}' "$INDEX" || true)"
fi

{
  echo "# INDEX"
  echo
  echo "## Canonical Notes (manual override)"
  if [[ -n "$MANUAL_SECTION" ]]; then
    echo "$MANUAL_SECTION" | sed '1d'
  else
    echo
    echo "- (add high-value canonical notes here)"
  fi
  echo
  echo "## Auto Index (generated)"
  echo
  echo "> Generated on $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo

  find "$ROOT" -type f -name "*.md" \
    -not -path "$ROOT/.obsidian/*" \
    -not -path "$ROOT/05_archive/*" \
    -not -path "$ROOT/06_system/INDEX.md" \
    | sort \
    | while read -r f; do
        rel="${f#$ROOT/}"
        title="$(awk 'NR==1{sub(/^# /,""); print; exit}' "$f")"
        if [[ -z "$title" ]]; then
          title="$(basename "$f" .md)"
        fi
        desc="$(awk 'NF{gsub(/^[#>-]+[[:space:]]*/, ""); print; exit}' "$f")"
        desc="${desc:-No summary yet.}"
        echo "- \\`$rel\\` — **$title**: $desc"
      done
} > "$TMP"

mv "$TMP" "$INDEX"
echo "Rebuilt $INDEX"
SH

chmod +x "$VAULT_PATH/06_system/rebuild_index.sh"

echo "Bootstrapped $VAULT_TYPE vault at: $VAULT_PATH"
echo "Next: run $VAULT_PATH/06_system/rebuild_index.sh"
